apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: demok8s
  annotations:
    kubernetes.io/ingress.class: nginx
# annotations เป็นการกำหนดค่าเพิ่มเติมสำหรับ Ingress โดยในที่นี้เราจะกำหนดให้ Ingress นี้ใช้ Ingress Controller ที่ชื่อว่า nginx และเราจะกำหนดให้ Ingress นี้อยู่ใน namespace ชื่อ demok8s เพื่อให้เราสามารถจัดการกับทรัพยากรที่เกี่ยวข้องกับ Ingress นี้ได้ง่ายขึ้น และเราจะกำหนดให้ Ingress นี้มีชื่อว่า ingress-service เพื่อให้เราสามารถอ้างอิงถึง Ingress นี้ได้ง่ายขึ้น และเราจะกำหนดให้ Ingress นี้มี annotation เพิ่มเติมเพื่อให้สามารถใช้ regular expression ในการกำหนด path ได้
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
# คิแ อการกำหนดกฎการเข้าถึงสำหรับ Ingress โดยมีการกำหนด host และ path ที่จะเชื่อมต่อกับ service ต่างๆ ใน cluster pathType: Prefix หมายความว่า ทุก path ที่ขึ้นต้นด้วย /api/ จะถูกส่งไปยัง server-service และทุก path ที่ขึ้นต้นด้วย / จะถูกส่งไปยัง client-service
spec:
  ingressClassName: nginx
  rules:
  - host: todo.site
    http:
      paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 80