apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: demok8s
spec:
  # clusterIP: คือ IP ที่จะถูกกำหนดให้กับ Service นี้ใน Cluster
  # NodePort: คือ Port ที่จะถูกเปิดบน Node เพื่อให้สามารถเข้าถึง Service นี้จากภายนอก Cluster ได้
  # LoadBalancer: คือ การสร้าง Load Balancer ภายนอกเพื่อให้สามารถเข้าถึง Service นี้จากภายนอก Cluster ได้
  # ExternalName: คือ การสร้าง Service ที่ชี้ไปยัง External DNS Name
  type: NodePort
  # port: คือ Port ที่ Service จะรับฟัง และส่งต่อไปยัง targetPort
  # targetPort: คือ Port ที่ Container จะรับฟัง และ Service จะส่งต่อไปยัง Container
  # nodePort: คือ Port ที่จะถูกเปิดบน Node เพื่อให้สามารถเข้าถึง Service นี้จากภายนอก Cluster ได้ (ต้องอยู่ในช่วง 30000-32767) 
  # protocol: คือ Protocol ที่ Service จะใช้ (TCP, UDP, SCTP) 
  # TCP เป็น Protocol ที่ใช้สำหรับการสื่อสารที่ต้องการความน่าเชื่อถือ เช่น HTTP, HTTPS, MySQL เป็นต้น
  # UDP เป็น Protocol ที่ใช้สำหรับการสื่อสารที่ไม่ต้องการความน่าเชื่อถือ เช่น DNS, DHCP, SNMP เป็นต้น
  # SCTP เป็น Protocol ที่ใช้สำหรับการสื่อสารที่ต้องการความน่า เชื่อถือและมีการจัดการการเชื่อมต่อที่ซับซ้อน เช่น WebRTC, Diameter เป็นต้น
  # selector: คือ การเลือก Pod ที่จะถูกเชื่อมต่อกับ Service นี้ โดยใช้ Label Selector ซึ่งจะเลือก Pod ที่มี Label ตรงกับที่กำหนดใน selector
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: nginx
