apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration

discovery:
  bootstrapToken:
    token: "fk1eyu.szsrwyu3l3s98kum"
    apiServerEndpoint: "192.168.1.122:6443"
    caCertHashes:
      - "sha256:1205898d95b0bf9c2dc346dbc12c54e36d7b98509d3ee6ac4f41163f6cdeeac3"

nodeRegistration:
  name: worker-1
  criSocket: "unix:///run/containerd/containerd.sock"